language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6
    - unzip
install:
  - "[ $CXX = g++ ] && export CXX=g++-6 || true"
script:
  - make
  - ./addNumbers
  - ./test.sh
  - echo $encrypted_d1234_key
before_install:
  - echo $encrypted_d1234_key
  - openssl enc -aes-256-cbc -d -in assignment2-nehatambe.zip.enc -out assignment2-nehatambe.zip -base64 -K $encrypted_d1234_key -iv $encrypted_d1234_iv
  - unzip assignment2-nehatambe.zip

